import { RbacPermission } from "@/generated/prisma/client";

export type RbacRoutePermissionRule = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "*";
  pattern: RegExp;
  permission: RbacPermission | null;
  description: string;
};

export const RBAC_ROUTE_PERMISSION_RULES: RbacRoutePermissionRule[] = [
  { id: "billing-view", method: "GET", pattern: /^\/api\/billing\/(?:invoices|profile)(?:\/|$)/, permission: "BILLING_VIEW", description: "View billing records and profile" },
  { id: "billing-document-download", method: "GET", pattern: /^\/api\/billing\/(?:invoices|credit-notes)\/[^/]+\/pdf$/, permission: "BILLING_VIEW", description: "Download billing documents" },
  { id: "billing-document-send", method: "POST", pattern: /^\/api\/billing\/(?:invoices|credit-notes)\/[^/]+\/send-email$/, permission: "BILLING_MANAGE", description: "Send billing documents by email" },
  { id: "billing-exports", method: "GET", pattern: /^\/api\/billing\/exports(?:\/download)?$/, permission: "BILLING_VIEW", description: "Download billing and accounting exports" },
  { id: "billing-profile-manage", method: "PATCH", pattern: /^\/api\/billing\/profile$/, permission: "BILLING_MANAGE", description: "Update billing profile" },
  { id: "billing-plan-checkouts", method: "POST", pattern: /^\/api\/billing\/plan-checkouts(?:\/[^/]+\/verify)?$/, permission: "BILLING_MANAGE", description: "Create or verify billing plan checkouts" },
  { id: "billing-credit-purchases", method: "*", pattern: /^\/api\/billing\/credit-purchases(?:\/[^/]+\/verify)?$/, permission: "BILLING_MANAGE", description: "Create or verify wallet credit purchases" },
  { id: "billing-plan-checkouts-reconcile", method: "POST", pattern: /^\/api\/billing\/plan-checkouts\/reconcile$/, permission: "BILLING_MANAGE", description: "Reconcile plan checkout state" },
  { id: "billing-manual-reviews", method: "*", pattern: /^\/api\/billing\/ops\/manual-reviews(?:\/[^/]+\/(?:approve|reject))?$/, permission: "BILLING_MANAGE", description: "Review manual billing checkouts" },
  { id: "billing-refunds", method: "*", pattern: /^\/api\/billing\/refunds(?:\/reconcile)?$/, permission: "BILLING_MANAGE", description: "Manage billing refunds" },
  { id: "billing-subscription", method: "POST", pattern: /^\/api\/billing\/subscription\/(?:cancel|change-plan|check-expiry|free|resume|cashfree\/(?:create-order|verify))$/, permission: "BILLING_MANAGE", description: "Manage subscription lifecycle" },
  { id: "billing-usage-quota-alerts", method: "POST", pattern: /^\/api\/billing\/usage-quota-alerts(?:\/scan|\/[^/]+\/(?:acknowledge|resolve))$/, permission: "BILLING_MANAGE", description: "Manage usage quota alerts" },
  { id: "campaign-create", method: "POST", pattern: /^\/api\/campaigns$/, permission: "CAMPAIGN_CREATE", description: "Create campaign" },
  { id: "campaign-view", method: "GET", pattern: /^\/api\/campaigns$/, permission: "CAMPAIGN_VIEW", description: "View campaigns" },
  { id: "campaign-preflight", method: "POST", pattern: /^\/api\/campaigns\/preflight$/, permission: "CAMPAIGN_CREATE", description: "Validate campaign launch readiness" },
  { id: "campaign-send", method: "POST", pattern: /^\/api\/campaigns\/[^/]+\/(?:start|send)$/, permission: "CAMPAIGN_SEND", description: "Start campaign" },
  { id: "campaign-retarget-preview", method: "POST", pattern: /^\/api\/campaigns\/[^/]+\/retarget\/preview$/, permission: "CAMPAIGN_VIEW", description: "Preview campaign retargeting audience" },
  { id: "campaign-retarget-create", method: "POST", pattern: /^\/api\/campaigns\/[^/]+\/retarget$/, permission: "CAMPAIGN_CREATE", description: "Create campaign retargeting segment" },
  { id: "campaign-sequences", method: "*", pattern: /^\/api\/campaigns\/[^/]+\/sequence-steps$/, permission: "CAMPAIGN_CREATE", description: "Manage campaign sequences" },
  { id: "campaign-cancel", method: "POST", pattern: /^\/api\/campaigns\/[^/]+\/cancel$/, permission: "CAMPAIGN_CANCEL", description: "Cancel campaign" },
  { id: "campaign-analytics-sync", method: "POST", pattern: /^\/api\/campaigns\/[^/]+\/analytics\/sync$/, permission: "CAMPAIGN_ANALYTICS_VIEW", description: "Sync campaign analytics" },
  { id: "campaign-launch", method: "*", pattern: /^\/api\/campaign-launch(?:\/[^/]+\/confirm)?$/, permission: "CAMPAIGN_SEND", description: "Prepare and queue campaign launches" },
  { id: "campaign-failure-intelligence", method: "*", pattern: /^\/api\/campaign-failures(?:\/insights\/[^/]+\/(?:retry|status))?$/, permission: "CAMPAIGN_SEND", description: "Analyze and retry campaign failure groups" },
  { id: "campaign-throughput", method: "*", pattern: /^\/api\/campaign-throughput(?:\/[^/]+\/policy)?$/, permission: "CAMPAIGN_SEND", description: "View and manage campaign throughput policies" },
  { id: "campaign-reports", method: "*", pattern: /^\/api\/campaign-reports(?:\/[^/]+\/download)?$/, permission: "CAMPAIGN_ANALYTICS_VIEW", description: "Generate and download final campaign reports" },
  { id: "campaign-replies", method: "*", pattern: /^\/api\/campaign-replies(?:\/conversions|\/tasks\/[^/]+\/status)?$/, permission: "CAMPAIGN_ANALYTICS_VIEW", description: "Attribute campaign replies and manage conversions" },
  { id: "settings-timeline-backfill", method: "POST", pattern: /^\/api\/settings\/timeline\/backfill$/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "Run CRM timeline backfill" },
  { id: "template-variable-mappings", method: "*", pattern: /^\/api\/template-variable-mappings(?:\/preview)?$/, permission: "CAMPAIGN_CREATE", description: "Manage template variable mappings" },
  { id: "contact-export", method: "GET", pattern: /^\/api\/contacts\/export$/, permission: "CONTACT_EXPORT", description: "Export contacts" },
  { id: "contact-import-view", method: "GET", pattern: /^\/api\/contacts\/import$/, permission: "CONTACT_VIEW", description: "View contact import jobs" },
  { id: "contact-import-preview", method: "POST", pattern: /^\/api\/contacts\/import$/, permission: "CONTACT_UPDATE", description: "Preview contact imports" },
  { id: "contact-import-run", method: "POST", pattern: /^\/api\/contacts\/import\/[^/]+\/run$/, permission: "CONTACT_UPDATE", description: "Execute contact import jobs" },
  { id: "contact-segments-view", method: "GET", pattern: /^\/api\/contact-segments$/, permission: "CONTACT_VIEW", description: "View contact segments" },
  { id: "contact-segments-manage", method: "POST", pattern: /^\/api\/contact-segments(?:\/[^/]+\/preview)?$/, permission: "CONTACT_UPDATE", description: "Create and preview contact segments" },
  { id: "contact-delete", method: "DELETE", pattern: /^\/api\/contacts\/[^/]+$/, permission: "CONTACT_DELETE", description: "Delete contact" },
  { id: "inbox-queues-view", method: "GET", pattern: /^\/api\/inbox\/queues(?:\/[^/]+\/members)?$/, permission: "INBOX_VIEW", description: "View inbox queues" },
  { id: "inbox-queues-manage", method: "*", pattern: /^\/api\/inbox\/queues(?:\/[^/]+(?:\/members)?)?$/, permission: "INBOX_MANAGE_QUEUES", description: "Manage inbox queues and queue members" },
  { id: "inbox-agents-view", method: "GET", pattern: /^\/api\/inbox\/agents$/, permission: "INBOX_VIEW", description: "View inbox agent profiles" },
  { id: "inbox-agents-manage", method: "POST", pattern: /^\/api\/inbox\/agents$/, permission: "INBOX_MANAGE_AGENTS", description: "Manage inbox agent profiles and skills" },
  { id: "inbox-skills-view", method: "GET", pattern: /^\/api\/inbox\/skills(?:\/[^/]+)?$/, permission: "INBOX_VIEW", description: "View inbox skills" },
  { id: "inbox-skills-manage", method: "*", pattern: /^\/api\/inbox\/skills(?:\/[^/]+)?$/, permission: "INBOX_MANAGE_AGENTS", description: "Manage inbox skills" },
  { id: "inbox-reply-approvals-view", method: "GET", pattern: /^\/api\/inbox\/reply-approvals$/, permission: "INBOX_VIEW", description: "View inbox reply approvals" },
  { id: "inbox-reply-approvals-manage", method: "POST", pattern: /^\/api\/inbox\/reply-approvals\/[^/]+\/(?:approve|reject|cancel)$/, permission: "INBOX_REPLY", description: "Approve, reject, or cancel inbox replies" },
  { id: "inbox-monitoring-view", method: "GET", pattern: /^\/api\/inbox\/monitoring$/, permission: "INBOX_VIEW", description: "View live inbox supervisor monitoring" },
  { id: "inbox-analytics-view", method: "GET", pattern: /^\/api\/inbox\/analytics\/(?:summary|agents|queues|sla)$/, permission: "INBOX_VIEW", description: "View inbox supervisor analytics" },
  { id: "inbox-csat-settings-view", method: "GET", pattern: /^\/api\/inbox\/csat\/settings$/, permission: "INBOX_VIEW", description: "View inbox CSAT settings" },
  { id: "inbox-csat-settings-manage", method: "PATCH", pattern: /^\/api\/inbox\/csat\/settings$/, permission: "INBOX_MANAGE_QUEUES", description: "Manage inbox CSAT settings" },
  { id: "inbox-ai-assist", method: "POST", pattern: /^\/api\/inbox\/[^/]+\/ai\/(?:summary|suggestions)$/, permission: "INBOX_USE_AI", description: "Generate inbox AI summaries and reply suggestions" },
  { id: "inbox-agent-presence", method: "*", pattern: /^\/api\/inbox\/presence$/, permission: "INBOX_VIEW", description: "View and update inbox agent presence" },
  { id: "inbox-conversation-presence", method: "*", pattern: /^\/api\/inbox\/[^/]+\/presence$/, permission: "INBOX_VIEW", description: "View and update inbox conversation presence" },
  { id: "inbox-routing-rules-view", method: "GET", pattern: /^\/api\/inbox\/routing-rules(?:\/[^/]+)?$/, permission: "INBOX_VIEW", description: "View inbox routing rules" },
  { id: "inbox-routing-rules-manage", method: "*", pattern: /^\/api\/inbox\/routing-rules(?:\/[^/]+)?$/, permission: "INBOX_MANAGE_QUEUES", description: "Manage inbox routing rules" },
  { id: "inbox-conversation-queue", method: "PATCH", pattern: /^\/api\/inbox\/[^/]+\/queue$/, permission: "INBOX_ASSIGN", description: "Move conversation between queues" },
  { id: "inbox-conversation-assignment", method: "POST", pattern: /^\/api\/inbox\/[^/]+\/(?:assignment|route)$/, permission: "INBOX_ASSIGN", description: "Assign or route inbox conversations" },
  { id: "message-send-template", method: "POST", pattern: /^\/api\/messages\/send-template$/, permission: "CAMPAIGN_SEND", description: "Send template messages" },
  { id: "message-send-single-template", method: "POST", pattern: /^\/api\/messages\/single-template$/, permission: "CAMPAIGN_SEND", description: "Send single messages" },
  { id: "message-cancel", method: "POST", pattern: /^\/api\/messages\/[^/]+\/cancel$/, permission: "CAMPAIGN_CANCEL", description: "Cancel scheduled messages" },
  { id: "message-translation", method: "POST", pattern: /^\/api\/messages\/[^/]+\/translation$/, permission: "INBOX_USE_AI", description: "Translate inbox messages with AI assistance" },
  { id: "whatsapp-settings-manage", method: "*", pattern: /^\/api\/whatsapp\/settings(?:\/|$)/, permission: "WHATSAPP_SETTINGS_MANAGE", description: "Manage WhatsApp settings" },
  { id: "whatsapp-account-view", method: "GET", pattern: /^\/api\/whatsapp\/accounts$/, permission: "WHATSAPP_SETTINGS_VIEW", description: "View WhatsApp account connection" },
  { id: "whatsapp-account-manage", method: "POST", pattern: /^\/api\/whatsapp\/(?:accounts|credentials|embedded-signup\/(?:complete|events)|phone-numbers\/[^/]+\/status|webhooks\/subscribe)$/, permission: "WHATSAPP_SETTINGS_MANAGE", description: "Manage WhatsApp account connection" },
  { id: "whatsapp-catalogs-view", method: "GET", pattern: /^\/api\/whatsapp\/catalogs$/, permission: "WHATSAPP_SETTINGS_VIEW", description: "View WhatsApp catalogs" },
  { id: "whatsapp-catalogs-manage", method: "POST", pattern: /^\/api\/whatsapp\/catalogs$/, permission: "WHATSAPP_SETTINGS_MANAGE", description: "Sync WhatsApp catalogs" },
  { id: "whatsapp-catalog-products-view", method: "GET", pattern: /^\/api\/whatsapp\/catalogs\/[^/]+\/products$/, permission: "WHATSAPP_SETTINGS_VIEW", description: "View WhatsApp catalog products" },
  { id: "whatsapp-catalog-products-sync", method: "POST", pattern: /^\/api\/whatsapp\/catalogs\/[^/]+\/products\/sync$/, permission: "WHATSAPP_SETTINGS_MANAGE", description: "Sync WhatsApp catalog products" },
  { id: "whatsapp-flows-view", method: "GET", pattern: /^\/api\/whatsapp-flows(?:\/[^/]+)?$/, permission: "WHATSAPP_SETTINGS_VIEW", description: "View WhatsApp Flows" },
  { id: "whatsapp-flows-manage", method: "*", pattern: /^\/api\/whatsapp-flows(?:\/[^/]+(?:\/send-test)?)?$/, permission: "WHATSAPP_SETTINGS_MANAGE", description: "Create, update, and test WhatsApp Flows" },
  { id: "whatsapp-template-sync", method: "POST", pattern: /^\/api\/whatsapp\/templates\/sync$/, permission: "TEMPLATE_SYNC", description: "Sync WhatsApp templates" },
  { id: "template-media-assets", method: "*", pattern: /^\/api\/templates\/media-assets$/, permission: "TEMPLATE_SYNC", description: "Upload WhatsApp template media samples" },
  { id: "template-submit", method: "POST", pattern: /^\/api\/templates\/[^/]+\/submit$/, permission: "TEMPLATE_SYNC", description: "Submit WhatsApp templates to Meta" },
  { id: "automation-executions-view", method: "GET", pattern: /^\/api\/automation\/executions(?:\/[^/]+)?$/, permission: "AUTOMATION_EXECUTION_VIEW", description: "View automation execution logs" },
  { id: "automation-monitoring-view", method: "GET", pattern: /^\/api\/automation\/monitoring\/overview$/, permission: "AUTOMATION_MONITORING_VIEW", description: "View automation monitoring overview" },
  { id: "automation-monitoring-run-checks", method: "POST", pattern: /^\/api\/automation\/monitoring\/run-checks$/, permission: "AUTOMATION_MONITORING_RUN_CHECKS", description: "Run automation monitoring checks" },
  { id: "automation-alerts-view", method: "GET", pattern: /^\/api\/automation\/alerts(?:\/[^/]+)?$/, permission: "AUTOMATION_ALERT_VIEW", description: "View automation alerts" },
  { id: "automation-alerts-manage", method: "POST", pattern: /^\/api\/automation\/alerts\/[^/]+\/(?:acknowledge|resolve|mute)$/, permission: "AUTOMATION_ALERT_MANAGE", description: "Manage automation alerts" },
  { id: "automation-flow-analytics-view", method: "GET", pattern: /^\/api\/automation\/flows\/[^/]+\/analytics$/, permission: "AUTOMATION_ANALYTICS_VIEW", description: "View automation flow analytics" },
  { id: "automation-flow-draft-edit", method: "PATCH", pattern: /^\/api\/automation\/flows\/[^/]+\/draft$/, permission: "AUTOMATION_FLOW_EDIT", description: "Edit automation draft graph" },
  { id: "automation-flow-test", method: "*", pattern: /^\/api\/automation\/flows\/[^/]+\/test(?:\/|$)/, permission: "AUTOMATION_FLOW_TEST", description: "Run automation live tests" },
  { id: "automation-flow-publish", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/publish$/, permission: "AUTOMATION_FLOW_PUBLISH", description: "Publish automation flow" },
  { id: "automation-flow-request-publish", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/publish-requests$/, permission: "AUTOMATION_FLOW_REQUEST_PUBLISH", description: "Request automation publish approval" },
  { id: "automation-flow-pause", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/pause$/, permission: "AUTOMATION_FLOW_PAUSE", description: "Pause automation flow" },
  { id: "automation-flow-resume", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/resume$/, permission: "AUTOMATION_FLOW_RESUME", description: "Resume automation flow" },
  { id: "automation-flow-archive", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/archive$/, permission: "AUTOMATION_FLOW_ARCHIVE", description: "Archive automation flow" },
  { id: "automation-flow-rollback", method: "POST", pattern: /^\/api\/automation\/flows\/[^/]+\/versions\/[^/]+\/rollback$/, permission: "AUTOMATION_FLOW_ROLLBACK", description: "Rollback automation flow version" },
  { id: "automation-flow-versions-view", method: "GET", pattern: /^\/api\/automation\/flows\/[^/]+\/versions(?:\/[^/]+)?$/, permission: "AUTOMATION_FLOW_VIEW", description: "View automation flow versions" },
  { id: "automation-publish-requests-approve", method: "POST", pattern: /^\/api\/automation\/publish-requests\/[^/]+\/approve$/, permission: "AUTOMATION_FLOW_APPROVE_PUBLISH", description: "Approve automation publish request" },
  { id: "automation-publish-requests-reject", method: "POST", pattern: /^\/api\/automation\/publish-requests\/[^/]+\/reject$/, permission: "AUTOMATION_FLOW_REJECT_PUBLISH", description: "Reject automation publish request" },
  { id: "automation-publish-requests-cancel", method: "POST", pattern: /^\/api\/automation\/publish-requests\/[^/]+\/cancel$/, permission: "AUTOMATION_FLOW_REQUEST_PUBLISH", description: "Cancel own automation publish request" },
  { id: "automation-publish-requests-view", method: "GET", pattern: /^\/api\/automation\/publish-requests(?:\/[^/]+)?$/, permission: "AUTOMATION_FLOW_VIEW", description: "View automation publish requests" },
  { id: "automation-template-library-use", method: "POST", pattern: /^\/api\/automation\/flow-templates\/[^/]+\/use$/, permission: "AUTOMATION_TEMPLATE_LIBRARY_USE", description: "Use automation flow template" },
  { id: "api-key-manage", method: "*", pattern: /^\/api\/developer\/api-keys(?:\/|$)/, permission: "DEVELOPER_API_KEYS_MANAGE", description: "Manage developer API keys" },
  { id: "developer-webhooks-manage", method: "*", pattern: /^\/api\/developer\/webhooks(?:\/|$)/, permission: "DEVELOPER_WEBHOOKS_MANAGE", description: "Manage developer webhooks" },
  { id: "developer-maintenance-retention", method: "POST", pattern: /^\/api\/developer\/maintenance\/retention-cleanup$/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "Run developer data retention cleanup" },
  { id: "wallet-view", method: "GET", pattern: /^\/api\/wallet$/, permission: "WALLET_VIEW", description: "View wallet balance and transactions" },
  { id: "wallet-top-up", method: "POST", pattern: /^\/api\/wallet$/, permission: "BILLING_MANAGE", description: "Top up wallet balance" },
  { id: "reports-campaign-export", method: "GET", pattern: /^\/api\/reports\/campaign-analytics\/export$/, permission: "CAMPAIGN_ANALYTICS_VIEW", description: "Export campaign analytics reports" },
  { id: "reports-message-export", method: "GET", pattern: /^\/api\/reports\/messages\/export$/, permission: "INBOX_VIEW", description: "Export message reports" },
  { id: "subscription-renewals-scan", method: "POST", pattern: /^\/api\/billing\/subscription-renewals\/scan$/, permission: "BILLING_MANAGE", description: "Run subscription renewal scan" },
  { id: "billing-analytics-snapshot", method: "POST", pattern: /^\/api\/billing\/analytics\/snapshot$/, permission: "BILLING_MANAGE", description: "Generate billing analytics snapshots" },
  { id: "scheduled-plan-change-manage", method: "POST", pattern: /^\/api\/billing\/scheduled-plan-change\/(?:cancel-at-period-end|downgrade|undo|scan)$/, permission: "BILLING_MANAGE", description: "Manage scheduled billing plan changes" },
  { id: "platform-company-plan-manage", method: "POST", pattern: /^\/api\/platform\/companies\/[^/]+\/plan\/cancel$/, permission: "BILLING_MANAGE", description: "Cancel company plan from platform console" },
  { id: "privacy-request-view", method: "GET", pattern: /^\/api\/privacy\/requests$/, permission: "PRIVACY_REQUEST_VIEW", description: "View privacy requests" },
  { id: "privacy-request-create", method: "POST", pattern: /^\/api\/privacy\/requests$/, permission: "PRIVACY_REQUEST_PROCESS", description: "Create privacy requests" },
  { id: "privacy-public-request", method: "POST", pattern: /^\/api\/privacy\/public\/request$/, permission: null, description: "Public privacy request intake" },
  { id: "privacy-request-process", method: "POST", pattern: /^\/api\/privacy\/requests\/[^/]+\/process$/, permission: "PRIVACY_REQUEST_PROCESS", description: "Process privacy request" },
  { id: "privacy-export-download", method: "GET", pattern: /^\/api\/privacy\/requests\/[^/]+\/download$/, permission: "PRIVACY_REQUEST_PROCESS", description: "Download privacy export" },
  { id: "compliance-evidence", method: "*", pattern: /^\/api\/system\/compliance(?:\/|$)/, permission: "COMPLIANCE_MANAGE", description: "Compliance evidence operations" },
  { id: "system-health-check", method: "POST", pattern: /^\/api\/system\/health\/check$/, permission: "SYSTEM_HEALTH_VIEW", description: "Run system health checks" },
  { id: "system-maintenance-mode", method: "*", pattern: /^\/api\/system\/maintenance-mode$/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "View and manage maintenance mode" },
  { id: "system-backups", method: "POST", pattern: /^\/api\/system\/backups\/(?:run|verify-latest)$/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "Run and verify backups" },
  { id: "system-audit-integrity", method: "POST", pattern: /^\/api\/system\/audit-integrity\/verify$/, permission: "COMPLIANCE_MANAGE", description: "Verify audit log integrity" },
  { id: "system-operations", method: "*", pattern: /^\/api\/system\/(?:data-retention|legal-holds|billing-reconciliation|dead-letter-queue|operation-lock|status-page|uptime-monitors)(?:\/|$)/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "System operation actions" },
  { id: "entitlement-overrides", method: "*", pattern: /^\/api\/system\/entitlements\/overrides$/, permission: "SYSTEM_OPERATIONS_MANAGE", description: "Feature entitlement overrides" },
  { id: "trust-center-manage", method: "*", pattern: /^\/api\/trust\/documents(?:\/|$)/, permission: "TRUST_CENTER_MANAGE", description: "Trust Center document management" },
  { id: "team-role-manage", method: "*", pattern: /^\/api\/team\/(?:roles|role-assignments)(?:\/|$)/, permission: "TEAM_MANAGE_ROLES", description: "Role and permission management" },
  { id: "team-invite-view", method: "GET", pattern: /^\/api\/team\/invites$/, permission: "TEAM_VIEW", description: "View team invites" },
  { id: "team-invite-manage", method: "POST", pattern: /^\/api\/team\/invites$/, permission: "TEAM_INVITE", description: "Create team invites" },
  { id: "team-invite-delete", method: "DELETE", pattern: /^\/api\/team\/invites\/[^/]+$/, permission: "TEAM_INVITE", description: "Revoke team invites" },
  { id: "team-member-manage", method: "*", pattern: /^\/api\/team\/(?:members\/[^/]+|[^/]+\/role)$/, permission: "TEAM_MANAGE_ROLES", description: "Manage team members" },
  { id: "public-api-message-send", method: "POST", pattern: /^\/api\/public\/messages\/send-template$/, permission: null, description: "Public API key scoped message send" },
  { id: "dev-whatsapp-bulk-test", method: "POST", pattern: /^\/api\/dev\/whatsapp-bulk-test$/, permission: null, description: "Developer-only WhatsApp bulk test endpoint" },
  { id: "provider-webhooks", method: "*", pattern: /^\/api\/webhooks\/(?:cashfree|whatsapp)$/, permission: null, description: "Provider webhook ingestion endpoints" },
];

export function getRequiredPermissionForRoute({
  pathname,
  method,
}: {
  pathname: string;
  method: string;
}) {
  const upperMethod = method.toUpperCase();
  return RBAC_ROUTE_PERMISSION_RULES.find(
    (rule) =>
      (rule.method === "*" || rule.method === upperMethod) &&
      rule.pattern.test(pathname),
  );
}
