-- AlterEnum
ALTER TYPE "TemplateStatus" ADD VALUE IF NOT EXISTS 'IN_APPEAL';
ALTER TYPE "TemplateStatus" ADD VALUE IF NOT EXISTS 'PENDING_DELETION';
ALTER TYPE "TemplateStatus" ADD VALUE IF NOT EXISTS 'DELETED';
ALTER TYPE "TemplateStatus" ADD VALUE IF NOT EXISTS 'DISABLED';
ALTER TYPE "TemplateStatus" ADD VALUE IF NOT EXISTS 'LIMIT_EXCEEDED';
